#include "codegen.h"

#include "co_abi.h"

#include <llvm/Bitcode/BitcodeReader.h>
#include <llvm/IR/AttributeMask.h>
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/LegacyPassManager.h>
#include <llvm/IR/MDBuilder.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Verifier.h>
#include <llvm/Linker/Linker.h>
#include <llvm/MC/TargetRegistry.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Support/FileSystem.h>
#include <llvm/Support/MemoryBuffer.h>
#include <llvm/Support/TargetSelect.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/Target/TargetMachine.h>
#include <llvm/Target/TargetOptions.h>
#include <llvm/TargetParser/Host.h>
#include <llvm/TargetParser/Triple.h>
#include <llvm/Transforms/IPO/Internalize.h>

#include <cstddef>
#include <functional>
#include <unordered_map>

namespace co {
using namespace mir;

// runtime/runtime.c as LLVM bitcode (generated by CMake from cmake/embed.cmake).
extern const unsigned char runtimeBitcode[];
extern const std::size_t runtimeBitcodeSize;

static_assert(offsetof(CoVec, ptr) == 0 && offsetof(CoVec, len) == 8 && offsetof(CoVec, cap) == 16 &&
                  sizeof(CoVec) == 24,
              "co.vec below must match CoVec");
static_assert(offsetof(CoMap, len) == offsetof(CoVec, len) && sizeof(CoMap) % 8 == 0,
              "co.map below must match CoMap");

namespace {

class CodeGen {
public:
  // `runtime` is the runtime's module, used to check runtime calls against
  // the real signatures; it is linked in after code generation.
  CodeGen(llvm::LLVMContext &ctx, llvm::Module &mod, const llvm::Module &runtime)
      : ctx_(ctx), mod_(mod), runtime_(runtime), b_(ctx), dl_(mod.getDataLayout()) {
    ptrTy_ = llvm::PointerType::getUnqual(ctx_);
    i64_ = llvm::Type::getInt64Ty(ctx_);
    i32_ = llvm::Type::getInt32Ty(ctx_);
    i1_ = llvm::Type::getInt1Ty(ctx_);
    f64_ = llvm::Type::getDoubleTy(ctx_);
    void_ = llvm::Type::getVoidTy(ctx_);
    vecTy_ = llvm::StructType::create(ctx_, {ptrTy_, i64_, i64_}, "co.vec");
    // Opaque apart from `len`, which is field 1 like in co.vec, so `len` reads either.
    mapTy_ = llvm::StructType::create(ctx_, {ptrTy_, i64_, llvm::ArrayType::get(i64_, sizeof(CoMap) / 8 - 2)},
                                      "co.map");
  }

  void run(const Module &m) {
    for (auto &f : m.funcs)
      declare(f.info);
    for (auto &f : m.funcs)
      emitFunction(f);
    for (auto &f : m.funcs)
      if (f.info->symbol == "co.main")
        emitMainWrapper(f.info);
  }

  // `func main() !`: the runtime calls co_main, which reports a returned error.
  void emitMainWrapper(FuncInfo *info) {
    auto *fn = llvm::Function::Create(llvm::FunctionType::get(void_, {}, false), llvm::Function::ExternalLinkage,
                                      "co_main", mod_);
    llvm::IRBuilder<> ib(llvm::BasicBlock::Create(ctx_, "entry", fn));
    llvm::Type *rt_ = lt(info->ret);
    llvm::Value *res = ib.CreateCall(fns_.at(info), {});
    llvm::Value *slot = ib.CreateAlloca(rt_);
    ib.CreateStore(res, slot);
    auto *fail = llvm::BasicBlock::Create(ctx_, "failed", fn);
    auto *done = llvm::BasicBlock::Create(ctx_, "done", fn);
    llvm::Value *tag = ib.CreateLoad(i64_, ib.CreateStructGEP(rt_, slot, 0));
    ib.CreateCondBr(ib.CreateICmpEQ(tag, llvm::ConstantInt::get(i64_, 1)), fail, done);
    ib.SetInsertPoint(fail);
    llvm::Value *payload = ib.CreateStructGEP(rt_, slot, 1);
    ib.CreateCall(rt("co_main_failed", void_, {ptrTy_}), {ib.CreateStructGEP(variantTy(info->ret, 1), payload, 0)});
    ib.CreateUnreachable();
    ib.SetInsertPoint(done);
    ib.CreateRetVoid();
  }

private:
  llvm::LLVMContext &ctx_;
  llvm::Module &mod_;
  const llvm::Module &runtime_;
  llvm::IRBuilder<> b_;
  const llvm::DataLayout &dl_;
  llvm::PointerType *ptrTy_;
  llvm::Type *i64_, *i32_, *i1_, *f64_, *void_;
  llvm::StructType *vecTy_, *mapTy_;
  std::unordered_map<StructInfo *, llvm::StructType *> structTys_;
  std::unordered_map<FuncInfo *, llvm::Function *> fns_;
  std::unordered_map<Type *, llvm::Function *> dropFns_, cloneFns_, printFns_;
  std::unordered_map<EnumInfo *, llvm::StructType *> enumTys_;

  // per-function state
  const Function *f_ = nullptr;
  llvm::Function *fn_ = nullptr;
  std::vector<llvm::Value *> slots_;
  std::vector<llvm::Value *> flags_; // drop flags
  std::vector<llvm::BasicBlock *> bbs_;
  llvm::BasicBlock *entry_ = nullptr;

  // ----- types -----

  llvm::Type *lt(Type *t) {
    switch (t->kind) {
    case TypeKind::Void: return void_;
    case TypeKind::Int: return i64_;
    case TypeKind::Float: return f64_;
    case TypeKind::IntN: return llvm::IntegerType::get(ctx_, t->bits);
    case TypeKind::Float32: return llvm::Type::getFloatTy(ctx_);
    case TypeKind::Ptr:
    case TypeKind::Nil: return ptrTy_;
    case TypeKind::Bool: return i1_;
    case TypeKind::String:
    case TypeKind::Error:
    case TypeKind::Slice: return vecTy_;
    case TypeKind::Ref: return ptrTy_;
    case TypeKind::Map: return mapTy_;
    case TypeKind::None: return i64_;
    case TypeKind::Enum: {
      // { i64 tag, [N x i64] payload } where the payload fits the largest variant.
      auto it = enumTys_.find(t->en);
      if (it != enumTys_.end())
        return it->second;
      auto *st = llvm::StructType::create(ctx_, "co." + t->en->name);
      enumTys_[t->en] = st;
      uint64_t size = 0;
      for (size_t v = 0; v < t->en->variants.size(); v++)
        size = std::max<uint64_t>(size, dl_.getTypeAllocSize(variantTy(t, (int)v)));
      st->setBody({i64_, llvm::ArrayType::get(i64_, (size + 7) / 8)});
      return st;
    }
    case TypeKind::Struct: {
      auto it = structTys_.find(t->st);
      if (it != structTys_.end())
        return it->second;
      auto *st = llvm::StructType::create(ctx_, "co." + t->st->name);
      structTys_[t->st] = st;
      std::vector<llvm::Type *> fields;
      for (auto &f : t->st->fields)
        fields.push_back(lt(f.type));
      st->setBody(fields);
      return st;
    }
    }
    return void_;
  }

  llvm::StructType *variantTy(Type *t, int v) {
    std::vector<llvm::Type *> fields;
    for (Type *f : t->en->variants[v].fields)
      fields.push_back(lt(f));
    return llvm::StructType::get(ctx_, fields);
  }

  // ----- maps -----

  int64_t allocSize(Type *t) { return (int64_t)dl_.getTypeAllocSize(lt(t)); }
  llvm::Value *keyKind(Type *m) {
    int k = m->key->kind == TypeKind::String ? CO_KEY_STR : m->key->kind == TypeKind::Bool ? CO_KEY_BOOL : CO_KEY_INT;
    return llvm::ConstantInt::get(i32_, k);
  }
  // Key and value sizes: the trailing arguments of most runtime map calls.
  std::vector<llvm::Value *> sizeArgs(Type *m, std::vector<llvm::Value *> first) {
    first.push_back(llvm::ConstantInt::get(i64_, allocSize(m->key)));
    first.push_back(llvm::ConstantInt::get(i64_, allocSize(m->inner)));
    return first;
  }
  // Common trailing arguments for runtime map lookups: kind, key size, value size.
  std::vector<llvm::Value *> mapArgs(Type *m, std::vector<llvm::Value *> first) {
    first.push_back(keyKind(m));
    return sizeArgs(m, std::move(first));
  }
  // co_map_alive / co_map_key_at / co_map_val_at for entry slot `i`.
  llvm::Value *mapAt(llvm::IRBuilder<> &ib, const char *fn, llvm::Type *ret, Type *m, llvm::Value *mp, llvm::Value *i) {
    return ib.CreateCall(rt(fn, ret, {ptrTy_, i64_, i64_, i64_}), sizeArgs(m, {mp, i}));
  }
  // Runs body(slot) for every live entry slot of the map at `mp`.
  void forEachEntry(llvm::IRBuilder<> &ib, Type *m, llvm::Value *mp, const std::function<void(llvm::Value *)> &body) {
    llvm::Function *fn = ib.GetInsertBlock()->getParent();
    llvm::Value *used = ib.CreateCall(rt("co_map_used", i64_, {ptrTy_}), {mp});
    emitLoop(ib, used, [&](llvm::Value *i) {
      auto *live = llvm::BasicBlock::Create(ctx_, "entry.live", fn);
      auto *next = llvm::BasicBlock::Create(ctx_, "entry.next", fn);
      llvm::Value *alive = mapAt(ib, "co_map_alive", i32_, m, mp, i);
      ib.CreateCondBr(ib.CreateICmpNE(alive, llvm::ConstantInt::get(i32_, 0)), live, next);
      ib.SetInsertPoint(live);
      body(i);
      ib.CreateBr(next);
      ib.SetInsertPoint(next);
    });
  }

  llvm::Value *sizeOf(Type *t) { return llvm::ConstantInt::get(i64_, dl_.getTypeAllocSize(lt(t))); }

  // ----- runtime -----

  // Declares runtime function `name`, which must exist in the runtime with
  // exactly this signature; its attributes (noreturn, readonly, ...) are copied over.
  llvm::FunctionCallee rt(const char *name, llvm::Type *ret, std::vector<llvm::Type *> params) {
    auto *fty = llvm::FunctionType::get(ret, params, false);
    const llvm::Function *def = runtime_.getFunction(name);
    if (!def || def->getFunctionType() != fty) {
      std::string got;
      llvm::raw_string_ostream os(got);
      if (def)
        def->getFunctionType()->print(os);
      else
        os << "nothing";
      llvm::report_fatal_error(llvm::Twine("internal compiler error: runtime function ") + name +
                               " is called as " + llvm::Twine(typeName(fty)) + " but the runtime defines " + got);
    }
    auto callee = mod_.getOrInsertFunction(name, fty);
    if (auto *fn = llvm::dyn_cast<llvm::Function>(callee.getCallee()))
      fn->setAttributes(def->getAttributes());
    return callee;
  }
  static std::string typeName(llvm::Type *t) {
    std::string s;
    llvm::raw_string_ostream os(s);
    t->print(os);
    return s;
  }

  void declare(FuncInfo *info) {
    std::vector<llvm::Type *> params;
    for (Type *p : info->params)
      params.push_back(lt(p));
    auto *fty = llvm::FunctionType::get(lt(info->ret), params, false);
    auto linkage = info->symbol == "co_main" ? llvm::Function::ExternalLinkage : llvm::Function::InternalLinkage;
    fns_[info] = llvm::Function::Create(fty, linkage, info->symbol, mod_);
  }

  llvm::AllocaInst *entryAlloca(llvm::Type *ty, const llvm::Twine &name = "") {
    llvm::IRBuilder<> eb(entry_, entry_->getFirstInsertionPt());
    return eb.CreateAlloca(ty, nullptr, name);
  }

  // ----- glue: loops, drop, clone -----

  // Emits `for i in 0..n { body(i) }` at builder `ib`.
  static void emitLoop(llvm::IRBuilder<> &ib, llvm::Value *n, const std::function<void(llvm::Value *)> &body) {
    llvm::Function *fn = ib.GetInsertBlock()->getParent();
    auto &ctx = fn->getContext();
    auto *i64 = llvm::Type::getInt64Ty(ctx);
    llvm::BasicBlock *pre = ib.GetInsertBlock();
    auto *head = llvm::BasicBlock::Create(ctx, "loop", fn);
    auto *bodyBB = llvm::BasicBlock::Create(ctx, "loop.body", fn);
    auto *done = llvm::BasicBlock::Create(ctx, "loop.done", fn);
    ib.CreateBr(head);
    ib.SetInsertPoint(head);
    auto *i = ib.CreatePHI(i64, 2, "i");
    i->addIncoming(llvm::ConstantInt::get(i64, 0), pre);
    ib.CreateCondBr(ib.CreateICmpSLT(i, n), bodyBB, done);
    ib.SetInsertPoint(bodyBB);
    body(i);
    auto *next = ib.CreateAdd(i, llvm::ConstantInt::get(i64, 1));
    i->addIncoming(next, ib.GetInsertBlock());
    ib.CreateBr(head);
    ib.SetInsertPoint(done);
  }

  llvm::Function *dropFn(Type *t) {
    auto it = dropFns_.find(t);
    if (it != dropFns_.end())
      return it->second;
    auto *fty = llvm::FunctionType::get(void_, {ptrTy_}, false);
    auto *fn = llvm::Function::Create(fty, llvm::Function::InternalLinkage, "co.drop." + t->str(), mod_);
    dropFns_[t] = fn;
    llvm::IRBuilder<> ib(llvm::BasicBlock::Create(ctx_, "entry", fn));
    llvm::Value *p = fn->getArg(0);
    switch (t->kind) {
    case TypeKind::String:
    case TypeKind::Error:
    case TypeKind::Slice: {
      llvm::Value *data = ib.CreateLoad(ptrTy_, ib.CreateStructGEP(vecTy_, p, 0));
      if (t->kind == TypeKind::Slice && t->inner->needsDrop()) {
        llvm::Value *len = ib.CreateLoad(i64_, ib.CreateStructGEP(vecTy_, p, 1));
        llvm::Function *elemDrop = dropFn(t->inner);
        llvm::Type *et = lt(t->inner);
        emitLoop(ib, len, [&](llvm::Value *i) { ib.CreateCall(elemDrop, {ib.CreateGEP(et, data, i)}); });
      }
      ib.CreateCall(rt("co_free", void_, {ptrTy_}), {data});
      break;
    }
    case TypeKind::Struct: {
      auto *st = lt(t);
      for (size_t i = 0; i < t->st->fields.size(); i++) {
        Type *ft = t->st->fields[i].type;
        if (ft->needsDrop())
          ib.CreateCall(dropFn(ft), {ib.CreateStructGEP(st, p, (unsigned)i)});
      }
      break;
    }
    case TypeKind::Enum:
      forEachVariant(ib, t, p, [&](int v, llvm::Value *payload) {
        auto *vt = variantTy(t, v);
        auto &fields = t->en->variants[v].fields;
        for (size_t i = 0; i < fields.size(); i++)
          if (fields[i]->needsDrop())
            ib.CreateCall(dropFn(fields[i]), {ib.CreateStructGEP(vt, payload, (unsigned)i)});
      });
      break;
    case TypeKind::Map:
      if (t->key->needsDrop() || t->inner->needsDrop())
        forEachEntry(ib, t, p, [&](llvm::Value *i) {
          if (t->key->needsDrop())
            ib.CreateCall(dropFn(t->key), {mapAt(ib, "co_map_key_at", ptrTy_, t, p, i)});
          if (t->inner->needsDrop())
            ib.CreateCall(dropFn(t->inner), {mapAt(ib, "co_map_val_at", ptrTy_, t, p, i)});
        });
      ib.CreateCall(rt("co_map_free", void_, {ptrTy_}), {p});
      break;
    default:
      break;
    }
    ib.CreateRetVoid();
    return fn;
  }

  // Emits a switch on the enum tag at `p`, calling body(variant, payloadPtr)
  // in each arm; continues after the switch.
  void forEachVariant(llvm::IRBuilder<> &ib, Type *t, llvm::Value *p,
                      const std::function<void(int, llvm::Value *)> &body) {
    llvm::Function *fn = ib.GetInsertBlock()->getParent();
    llvm::Type *et = lt(t);
    llvm::Value *tag = ib.CreateLoad(i64_, ib.CreateStructGEP(et, p, 0));
    llvm::Value *payload = ib.CreateStructGEP(et, p, 1);
    auto *done = llvm::BasicBlock::Create(ctx_, "variant.done", fn);
    auto *sw = ib.CreateSwitch(tag, done, (unsigned)t->en->variants.size());
    for (size_t v = 0; v < t->en->variants.size(); v++) {
      auto *bb = llvm::BasicBlock::Create(ctx_, "variant." + t->en->variants[v].name, fn);
      sw->addCase(llvm::ConstantInt::get(llvm::cast<llvm::IntegerType>(i64_), v), bb);
      ib.SetInsertPoint(bb);
      body((int)v, payload);
      ib.CreateBr(done);
    }
    ib.SetInsertPoint(done);
  }

  // Prints any value, given a pointer to it.
  llvm::Function *printFn(Type *t) {
    auto it = printFns_.find(t);
    if (it != printFns_.end())
      return it->second;
    auto *fty = llvm::FunctionType::get(void_, {ptrTy_}, false);
    auto *fn = llvm::Function::Create(fty, llvm::Function::InternalLinkage, "co.print." + t->str(), mod_);
    printFns_[t] = fn;
    llvm::IRBuilder<> ib(llvm::BasicBlock::Create(ctx_, "entry", fn));
    llvm::Value *p = fn->getArg(0);
    auto text = [&](const std::string &s) {
      ib.CreateCall(rt("co_print_cstr", void_, {ptrTy_}), {ib.CreateGlobalString(s)});
    };
    switch (t->kind) {
    case TypeKind::Int:
    case TypeKind::Float:
    case TypeKind::Bool:
    case TypeKind::IntN:
    case TypeKind::Float32:
    case TypeKind::Ptr: printScalar(ib, t, ib.CreateLoad(lt(t), p)); break;
    case TypeKind::String:
    case TypeKind::Error: ib.CreateCall(rt("co_print_str", void_, {ptrTy_}), {p}); break;
    case TypeKind::Ref: ib.CreateCall(printFn(t->inner), {ib.CreateLoad(ptrTy_, p)}); break;
    case TypeKind::Slice: {
      text("[");
      llvm::Value *data = ib.CreateLoad(ptrTy_, ib.CreateStructGEP(vecTy_, p, 0));
      llvm::Value *len = ib.CreateLoad(i64_, ib.CreateStructGEP(vecTy_, p, 1));
      llvm::Function *ep = printFn(t->inner);
      llvm::Type *et = lt(t->inner);
      emitLoop(ib, len, [&](llvm::Value *i) {
        auto *sep = llvm::BasicBlock::Create(ctx_, "sep", fn);
        auto *elem = llvm::BasicBlock::Create(ctx_, "elem", fn);
        ib.CreateCondBr(ib.CreateICmpNE(i, llvm::ConstantInt::get(i64_, 0)), sep, elem);
        ib.SetInsertPoint(sep);
        text(", ");
        ib.CreateBr(elem);
        ib.SetInsertPoint(elem);
        ib.CreateCall(ep, {ib.CreateGEP(et, data, i)});
      });
      text("]");
      break;
    }
    case TypeKind::Map: {
      text("{");
      llvm::Value *first = ib.CreateAlloca(i1_);
      ib.CreateStore(ib.getTrue(), first);
      forEachEntry(ib, t, p, [&](llvm::Value *i) {
        auto *sep = llvm::BasicBlock::Create(ctx_, "sep", fn);
        auto *item = llvm::BasicBlock::Create(ctx_, "item", fn);
        ib.CreateCondBr(ib.CreateLoad(i1_, first), item, sep);
        ib.SetInsertPoint(sep);
        text(", ");
        ib.CreateBr(item);
        ib.SetInsertPoint(item);
        ib.CreateStore(ib.getFalse(), first);
        ib.CreateCall(printFn(t->key), {mapAt(ib, "co_map_key_at", ptrTy_, t, p, i)});
        text(": ");
        ib.CreateCall(printFn(t->inner), {mapAt(ib, "co_map_val_at", ptrTy_, t, p, i)});
      });
      text("}");
      break;
    }
    case TypeKind::Struct: {
      auto *st = lt(t);
      text(t->st->name + "{");
      for (size_t i = 0; i < t->st->fields.size(); i++) {
        text((i ? ", " : "") + t->st->fields[i].name + ": ");
        ib.CreateCall(printFn(t->st->fields[i].type), {ib.CreateStructGEP(st, p, (unsigned)i)});
      }
      text("}");
      break;
    }
    case TypeKind::Enum:
      forEachVariant(ib, t, p, [&](int v, llvm::Value *payload) {
        auto &var = t->en->variants[v];
        text(var.name);
        if (var.fields.empty())
          return;
        auto *vt = variantTy(t, v);
        text("(");
        for (size_t i = 0; i < var.fields.size(); i++) {
          if (i)
            text(", ");
          ib.CreateCall(printFn(var.fields[i]), {ib.CreateStructGEP(vt, payload, (unsigned)i)});
        }
        text(")");
      });
      break;
    default:
      break;
    }
    ib.CreateRetVoid();
    return fn;
  }

  llvm::Function *cloneFn(Type *t) {
    auto it = cloneFns_.find(t);
    if (it != cloneFns_.end())
      return it->second;
    auto *fty = llvm::FunctionType::get(void_, {ptrTy_, ptrTy_}, false);
    auto *fn = llvm::Function::Create(fty, llvm::Function::InternalLinkage, "co.clone." + t->str(), mod_);
    cloneFns_[t] = fn;
    llvm::IRBuilder<> ib(llvm::BasicBlock::Create(ctx_, "entry", fn));
    llvm::Value *dst = fn->getArg(0), *src = fn->getArg(1);
    if (t->isCopy()) {
      ib.CreateStore(ib.CreateLoad(lt(t), src), dst);
    } else if (t->kind == TypeKind::String || t->kind == TypeKind::Error) {
      ib.CreateCall(rt("co_str_clone", void_, {ptrTy_, ptrTy_}), {dst, src});
    } else if (t->kind == TypeKind::Slice) {
      ib.CreateCall(rt("co_vec_clone_bits", void_, {ptrTy_, ptrTy_, i64_}), {dst, src, sizeOf(t->inner)});
      if (!t->inner->isCopy()) {
        llvm::Value *len = ib.CreateLoad(i64_, ib.CreateStructGEP(vecTy_, src, 1));
        llvm::Value *sd = ib.CreateLoad(ptrTy_, ib.CreateStructGEP(vecTy_, src, 0));
        llvm::Value *dd = ib.CreateLoad(ptrTy_, ib.CreateStructGEP(vecTy_, dst, 0));
        llvm::Function *ec = cloneFn(t->inner);
        llvm::Type *et = lt(t->inner);
        emitLoop(ib, len, [&](llvm::Value *i) {
          ib.CreateCall(ec, {ib.CreateGEP(et, dd, i), ib.CreateGEP(et, sd, i)});
        });
      }
    } else if (t->kind == TypeKind::Map) {
      ib.CreateCall(rt("co_map_clone_bits", void_, {ptrTy_, ptrTy_, i64_, i64_}), sizeArgs(t, {dst, src}));
      if (!t->key->isCopy() || !t->inner->isCopy()) {
        // The clone's entries sit at the same slots as the original's.
        forEachEntry(ib, t, src, [&](llvm::Value *i) {
          if (!t->key->isCopy())
            ib.CreateCall(cloneFn(t->key), {mapAt(ib, "co_map_key_at", ptrTy_, t, dst, i),
                                            mapAt(ib, "co_map_key_at", ptrTy_, t, src, i)});
          if (!t->inner->isCopy())
            ib.CreateCall(cloneFn(t->inner), {mapAt(ib, "co_map_val_at", ptrTy_, t, dst, i),
                                              mapAt(ib, "co_map_val_at", ptrTy_, t, src, i)});
        });
      }
    } else if (t->kind == TypeKind::Enum) {
      // Copy the bits (tag and copyable fields), then deep-clone owned fields.
      ib.CreateStore(ib.CreateLoad(lt(t), src), dst);
      llvm::Value *dpay = ib.CreateStructGEP(lt(t), dst, 1);
      forEachVariant(ib, t, src, [&](int v, llvm::Value *spay) {
        auto *vt = variantTy(t, v);
        auto &fields = t->en->variants[v].fields;
        for (size_t i = 0; i < fields.size(); i++)
          if (!fields[i]->isCopy())
            ib.CreateCall(cloneFn(fields[i]),
                          {ib.CreateStructGEP(vt, dpay, (unsigned)i), ib.CreateStructGEP(vt, spay, (unsigned)i)});
      });
    } else if (t->kind == TypeKind::Struct) {
      auto *st = lt(t);
      for (size_t i = 0; i < t->st->fields.size(); i++) {
        Type *ft = t->st->fields[i].type;
        llvm::Value *d = ib.CreateStructGEP(st, dst, (unsigned)i);
        llvm::Value *s = ib.CreateStructGEP(st, src, (unsigned)i);
        if (ft->isCopy())
          ib.CreateStore(ib.CreateLoad(lt(ft), s), d);
        else
          ib.CreateCall(cloneFn(ft), {d, s});
      }
    }
    ib.CreateRetVoid();
    return fn;
  }

  // ----- functions -----

  void emitFunction(const Function &f) {
    f_ = &f;
    fn_ = fns_.at(f.info);
    entry_ = llvm::BasicBlock::Create(ctx_, "entry", fn_);
    b_.SetInsertPoint(entry_);
    slots_.assign(f.locals.size(), nullptr);
    flags_.assign(f.locals.size(), nullptr);
    for (size_t i = 0; i < f.locals.size(); i++) {
      Type *t = f.locals[i].type;
      if (t->kind == TypeKind::Void)
        continue;
      const std::string &n = f.locals[i].name;
      slots_[i] = b_.CreateAlloca(lt(t), nullptr, n.empty() ? "_" + std::to_string(i) : n);
      if (t->needsDrop()) {
        flags_[i] = b_.CreateAlloca(i1_, nullptr, "dropflag");
        b_.CreateStore(b_.getFalse(), flags_[i]);
      }
    }
    for (int p = 1; p <= f.numParams; p++) {
      b_.CreateStore(fn_->getArg(p - 1), slots_[p]);
      if (flags_[p])
        b_.CreateStore(b_.getTrue(), flags_[p]);
    }
    bbs_.clear();
    for (size_t i = 0; i < f.blocks.size(); i++)
      bbs_.push_back(llvm::BasicBlock::Create(ctx_, "bb" + std::to_string(i), fn_));
    b_.CreateBr(bbs_[0]);

    for (size_t i = 0; i < f.blocks.size(); i++) {
      b_.SetInsertPoint(bbs_[i]);
      for (auto &s : f.blocks[i].stmts)
        emitStmt(s);
      emitTerm(f.blocks[i].term);
    }
  }

  void panicIf(llvm::Value *cond, const char *what, llvm::Value *a = nullptr, llvm::Value *c = nullptr) {
    auto *bad = llvm::BasicBlock::Create(ctx_, "panic", fn_);
    auto *ok = llvm::BasicBlock::Create(ctx_, "ok", fn_);
    b_.CreateCondBr(cond, bad, ok, llvm::MDBuilder(ctx_).createUnlikelyBranchWeights());
    b_.SetInsertPoint(bad);
    if (a)
      b_.CreateCall(rt("co_panic_bounds", void_, {i64_, i64_}), {a, c});
    else
      b_.CreateCall(rt("co_panic", void_, {ptrTy_}), {b_.CreateGlobalString(what)});
    b_.CreateUnreachable();
    b_.SetInsertPoint(ok);
  }

  llvm::Value *addr(const Place &p, Type *&ty) {
    llvm::Value *v = slots_[p.local];
    ty = f_->locals[p.local].type;
    for (auto &pr : p.proj) {
      switch (pr.kind) {
      case Proj::Deref:
        v = b_.CreateLoad(ptrTy_, v);
        ty = ty->inner;
        break;
      case Proj::Field:
        v = b_.CreateStructGEP(lt(ty), v, (unsigned)pr.field);
        ty = ty->st->fields[pr.field].type;
        break;
      case Proj::Index: {
        llvm::Value *data = b_.CreateLoad(ptrTy_, b_.CreateStructGEP(vecTy_, v, 0));
        llvm::Value *len = b_.CreateLoad(i64_, b_.CreateStructGEP(vecTy_, v, 1));
        llvm::Value *idx = b_.CreateLoad(i64_, slots_[pr.indexLocal]);
        panicIf(b_.CreateICmpUGE(idx, len), nullptr, idx, len);
        ty = ty->inner;
        v = b_.CreateGEP(lt(ty), data, idx);
        break;
      }
      case Proj::VariantField: {
        llvm::Value *payload = b_.CreateStructGEP(lt(ty), v, 1);
        v = b_.CreateStructGEP(variantTy(ty, pr.variant), payload, (unsigned)pr.field);
        ty = ty->en->variants[pr.variant].fields[pr.field];
        break;
      }
      }
    }
    return v;
  }

  llvm::Value *operand(const Operand &o) {
    switch (o.kind) {
    case Operand::Const:
      switch (o.c.kind) {
      case Constant::Int: return llvm::ConstantInt::get(lt(o.type), o.c.i, true);
      case Constant::Float: return llvm::ConstantFP::get(lt(o.type), o.c.f);
      case Constant::Bool: return llvm::ConstantInt::get(i1_, o.c.b);
      case Constant::Zero: return llvm::Constant::getNullValue(lt(o.type));
      }
      return nullptr;
    case Operand::Copy:
    case Operand::Move: {
      Type *ty;
      llvm::Value *a = addr(o.place, ty);
      llvm::Value *v = b_.CreateLoad(lt(ty), a);
      bool consumes = true; // moving the local itself, or an enum payload out of it
      for (auto &pr : o.place.proj)
        consumes &= pr.kind == Proj::VariantField;
      if (o.kind == Operand::Move && consumes && flags_[o.place.local])
        b_.CreateStore(b_.getFalse(), flags_[o.place.local]);
      return v;
    }
    }
    return nullptr;
  }

  // Arithmetic and comparisons; integers are signed unless `isSigned` is false.
  llvm::Value *binary(BinOp op, bool isFloat, bool isSigned, llvm::Value *l, llvm::Value *r) {
    if (isFloat) {
      switch (op) {
      case BinOp::Add: return b_.CreateFAdd(l, r);
      case BinOp::Sub: return b_.CreateFSub(l, r);
      case BinOp::Mul: return b_.CreateFMul(l, r);
      case BinOp::Div: return b_.CreateFDiv(l, r);
      case BinOp::Eq: return b_.CreateFCmpOEQ(l, r);
      case BinOp::Ne: return b_.CreateFCmpUNE(l, r);
      case BinOp::Lt: return b_.CreateFCmpOLT(l, r);
      case BinOp::Le: return b_.CreateFCmpOLE(l, r);
      case BinOp::Gt: return b_.CreateFCmpOGT(l, r);
      case BinOp::Ge: return b_.CreateFCmpOGE(l, r);
      default: return nullptr;
      }
    }
    switch (op) {
    case BinOp::Add: return b_.CreateAdd(l, r);
    case BinOp::Sub: return b_.CreateSub(l, r);
    case BinOp::Mul: return b_.CreateMul(l, r);
    case BinOp::Div:
    case BinOp::Rem: {
      auto *ty = llvm::cast<llvm::IntegerType>(l->getType());
      panicIf(b_.CreateICmpEQ(r, llvm::ConstantInt::get(ty, 0)), "integer division by zero");
      if (!isSigned)
        return op == BinOp::Div ? b_.CreateUDiv(l, r) : b_.CreateURem(l, r);
      auto *minInt = llvm::ConstantInt::get(ty, llvm::APInt::getSignedMinValue(ty->getBitWidth()));
      auto *minus1 = llvm::ConstantInt::get(ty, -1, true);
      panicIf(b_.CreateAnd(b_.CreateICmpEQ(l, minInt), b_.CreateICmpEQ(r, minus1)), "integer overflow in division");
      return op == BinOp::Div ? b_.CreateSDiv(l, r) : b_.CreateSRem(l, r);
    }
    case BinOp::Eq: return b_.CreateICmpEQ(l, r);
    case BinOp::Ne: return b_.CreateICmpNE(l, r);
    case BinOp::Lt: return isSigned ? b_.CreateICmpSLT(l, r) : b_.CreateICmpULT(l, r);
    case BinOp::Le: return isSigned ? b_.CreateICmpSLE(l, r) : b_.CreateICmpULE(l, r);
    case BinOp::Gt: return isSigned ? b_.CreateICmpSGT(l, r) : b_.CreateICmpUGT(l, r);
    case BinOp::Ge: return isSigned ? b_.CreateICmpSGE(l, r) : b_.CreateICmpUGE(l, r);
    default: return nullptr;
    }
  }

  // Calls a runtime function that writes a co.vec result through an out pointer.
  llvm::Value *viaOut(const char *name, std::vector<llvm::Type *> types, std::vector<llvm::Value *> args) {
    llvm::Value *out = entryAlloca(vecTy_);
    types.insert(types.begin(), ptrTy_);
    args.insert(args.begin(), out);
    b_.CreateCall(rt(name, void_, types), args);
    return b_.CreateLoad(vecTy_, out);
  }

  void printValue(Type *t, llvm::Value *v) {
    if (t->isRef()) {
      b_.CreateCall(printFn(t->inner), {v});
      return;
    }
    if (t->isNumeric() || t->kind == TypeKind::Bool || t->isPtr())
      printScalar(b_, t, v);
  }

  // Prints a number, bool or pointer.
  void printScalar(llvm::IRBuilder<> &ib, Type *t, llvm::Value *v) {
    switch (t->kind) {
    case TypeKind::Int: ib.CreateCall(rt("co_print_int", void_, {i64_}), {v}); break;
    case TypeKind::IntN:
      if (t->isUnsigned)
        ib.CreateCall(rt("co_print_uint", void_, {i64_}), {ib.CreateZExt(v, i64_)});
      else
        ib.CreateCall(rt("co_print_int", void_, {i64_}), {ib.CreateSExt(v, i64_)});
      break;
    case TypeKind::Float: ib.CreateCall(rt("co_print_float", void_, {f64_}), {v}); break;
    case TypeKind::Float32: ib.CreateCall(rt("co_print_float", void_, {f64_}), {ib.CreateFPExt(v, f64_)}); break;
    case TypeKind::Bool: ib.CreateCall(rt("co_print_bool", void_, {i32_}), {ib.CreateZExt(v, i32_)}); break;
    case TypeKind::Ptr: ib.CreateCall(rt("co_print_ptr", void_, {ptrTy_}), {v}); break;
    default: break;
    }
  }

  // Numeric conversion, as in int32(x). Float-to-integer saturates (NaN gives 0).
  llvm::Value *convert(llvm::Value *v, Type *from, Type *to) {
    llvm::Type *dt = lt(to);
    if (from == to)
      return v;
    if (from->isInteger() && to->isInteger())
      return b_.CreateIntCast(v, dt, from->isSigned());
    if (from->isInteger())
      return from->isSigned() ? b_.CreateSIToFP(v, dt) : b_.CreateUIToFP(v, dt);
    if (to->isInteger())
      return b_.CreateIntrinsic(to->isSigned() ? llvm::Intrinsic::fptosi_sat : llvm::Intrinsic::fptoui_sat,
                                {dt, v->getType()}, {v});
    return b_.CreateFPCast(v, dt);
  }

  // ----- calling C -----

  // Declares C function `f`. Integers narrower than int are extended by the
  // caller, as C compilers expect.
  llvm::FunctionCallee externFn(FuncInfo *f) {
    std::vector<llvm::Type *> params;
    for (Type *p : f->params)
      params.push_back(lt(p));
    auto *fty = llvm::FunctionType::get(f->ret->kind == TypeKind::Void ? void_ : lt(f->ret), params, f->variadic);
    auto callee = mod_.getOrInsertFunction(f->symbol, fty);
    auto ext = [](Type *t) {
      if (t->kind == TypeKind::Bool || (t->kind == TypeKind::IntN && t->bits < 32))
        return t->isSigned() ? llvm::Attribute::SExt : llvm::Attribute::ZExt;
      return llvm::Attribute::None;
    };
    if (auto *fn = llvm::dyn_cast<llvm::Function>(callee.getCallee()); fn && fn->getFunctionType() == fty) {
      for (size_t i = 0; i < f->params.size(); i++)
        if (auto a = ext(f->params[i]); a != llvm::Attribute::None)
          fn->addParamAttr((unsigned)i, a);
      if (auto a = ext(f->ret); a != llvm::Attribute::None)
        fn->addRetAttr(a);
    }
    return callee;
  }

  // A call to C. Strings become NUL-terminated copies (in a stack buffer when
  // they fit) and slices their element pointers, both only for the call;
  // variadic arguments get C's default promotions.
  llvm::Value *externCall(const Rvalue &rv) {
    FuncInfo *f = rv.func;
    llvm::FunctionCallee callee = externFn(f);
    std::vector<llvm::Value *> args;
    std::vector<std::pair<llvm::Value *, llvm::Value *>> cstrs; // (C string, stack buffer)
    const int64_t bufSize = 256;
    for (size_t i = 0; i < rv.ops.size(); i++) {
      Type *t = rv.ops[i].type;
      llvm::Value *v = operand(rv.ops[i]);
      if (t->isRef() && t->inner->kind == TypeKind::String) {
        llvm::Value *buf = entryAlloca(llvm::ArrayType::get(llvm::Type::getInt8Ty(ctx_), bufSize), "cstr.buf");
        v = b_.CreateCall(rt("co_cstr_begin", ptrTy_, {ptrTy_, ptrTy_, i64_}),
                          {v, buf, llvm::ConstantInt::get(i64_, bufSize)});
        cstrs.push_back({v, buf});
      } else if (t->isRef() && t->inner->kind == TypeKind::Slice) {
        v = b_.CreateLoad(ptrTy_, b_.CreateStructGEP(vecTy_, v, 0));
      } else if (i >= f->params.size()) {
        if (t->kind == TypeKind::Float32)
          v = b_.CreateFPExt(v, f64_);
        else if (t->kind == TypeKind::Bool || (t->kind == TypeKind::IntN && t->bits < 32))
          v = b_.CreateIntCast(v, i32_, t->isSigned());
      }
      args.push_back(v);
    }
    llvm::Value *res = b_.CreateCall(callee, args);
    for (auto &[p, buf] : cstrs)
      b_.CreateCall(rt("co_cstr_end", void_, {ptrTy_, ptrTy_}), {p, buf});
    return f->ret->kind == TypeKind::Void ? nullptr : res;
  }

  llvm::Value *rvalue(const Rvalue &rv) {
    switch (rv.kind) {
    case Rvalue::Use:
      return operand(rv.ops[0]);
    case Rvalue::BinaryOp: {
      llvm::Value *l = operand(rv.ops[0]);
      llvm::Value *r = operand(rv.ops[1]);
      Type *t = rv.ops[0].type;
      return binary(rv.bop, t->isFloat(), !t->isInteger() || t->isSigned(), l, r);
    }
    case Rvalue::UnaryOp: {
      llvm::Value *v = operand(rv.ops[0]);
      if (rv.uop == UnOp::Not)
        return b_.CreateNot(v);
      return rv.type->isFloat() ? b_.CreateFNeg(v) : b_.CreateNeg(v);
    }
    case Rvalue::Ref: {
      Type *ty;
      return addr(rv.place, ty);
    }
    case Rvalue::Discriminant: {
      Type *ty;
      llvm::Value *a = addr(rv.place, ty);
      return b_.CreateLoad(i64_, b_.CreateStructGEP(lt(ty), a, 0));
    }
    case Rvalue::Aggregate: {
      if (rv.variant >= 0) {
        llvm::Type *et = lt(rv.type);
        std::vector<llvm::Value *> vals;
        for (auto &op : rv.ops)
          vals.push_back(operand(op));
        llvm::Value *tmp = entryAlloca(et);
        b_.CreateStore(llvm::Constant::getNullValue(et), tmp);
        b_.CreateStore(llvm::ConstantInt::get(i64_, rv.variant), b_.CreateStructGEP(et, tmp, 0));
        auto *vt = variantTy(rv.type, rv.variant);
        llvm::Value *payload = b_.CreateStructGEP(et, tmp, 1);
        for (size_t i = 0; i < vals.size(); i++)
          b_.CreateStore(vals[i], b_.CreateStructGEP(vt, payload, (unsigned)i));
        return b_.CreateLoad(et, tmp);
      }
      llvm::Value *agg = llvm::UndefValue::get(lt(rv.type));
      for (size_t i = 0; i < rv.ops.size(); i++)
        agg = b_.CreateInsertValue(agg, operand(rv.ops[i]), {(unsigned)i});
      return agg;
    }
    case Rvalue::SliceLit: {
      Type *et = rv.type->inner;
      llvm::Value *vec = entryAlloca(vecTy_);
      llvm::Value *tmp = entryAlloca(lt(et));
      b_.CreateCall(rt("co_vec_new", void_, {ptrTy_, i64_, i64_}),
                    {vec, llvm::ConstantInt::get(i64_, rv.ops.size()), sizeOf(et)});
      for (auto &op : rv.ops) {
        b_.CreateStore(operand(op), tmp);
        b_.CreateCall(rt("co_vec_push", void_, {ptrTy_, ptrTy_, i64_}), {vec, tmp, sizeOf(et)});
      }
      return b_.CreateLoad(vecTy_, vec);
    }
    case Rvalue::Call: {
      if (rv.func->isExtern)
        return externCall(rv);
      std::vector<llvm::Value *> args;
      for (auto &op : rv.ops)
        args.push_back(operand(op));
      llvm::Value *v = b_.CreateCall(fns_.at(rv.func), args);
      return rv.func->ret->kind == TypeKind::Void ? nullptr : v;
    }
    case Rvalue::Builtin:
      return builtin(rv);
    }
    return nullptr;
  }

  llvm::Value *builtin(const Rvalue &rv) {
    std::vector<llvm::Value *> a;
    for (auto &op : rv.ops)
      a.push_back(operand(op));
    switch (rv.builtin) {
    case BuiltinOp::Print:
    case BuiltinOp::Println:
      for (size_t i = 0; i < a.size(); i++) {
        if (i && rv.builtin == BuiltinOp::Println)
          b_.CreateCall(rt("co_print_space", void_, {}), {});
        printValue(rv.ops[i].type, a[i]);
      }
      if (rv.builtin == BuiltinOp::Println)
        b_.CreateCall(rt("co_print_newline", void_, {}), {});
      return nullptr;
    case BuiltinOp::Len:
      return b_.CreateLoad(i64_, b_.CreateStructGEP(vecTy_, a[0], 1));
    case BuiltinOp::Append:
    case BuiltinOp::Push: {
      Type *elemTy = rv.ops[1].type;
      llvm::Value *elem = entryAlloca(lt(elemTy));
      b_.CreateStore(a[1], elem);
      llvm::Value *vec = a[0];
      if (rv.builtin == BuiltinOp::Append) {
        vec = entryAlloca(vecTy_);
        b_.CreateStore(a[0], vec);
      }
      b_.CreateCall(rt("co_vec_push", void_, {ptrTy_, ptrTy_, i64_}), {vec, elem, sizeOf(elemTy)});
      return rv.builtin == BuiltinOp::Append ? b_.CreateLoad(vecTy_, vec) : nullptr;
    }
    case BuiltinOp::Clone: {
      Type *t = rv.type;
      if (t->isCopy())
        return b_.CreateLoad(lt(t), a[0]);
      llvm::Value *out = entryAlloca(lt(t));
      b_.CreateCall(cloneFn(t), {out, a[0]});
      return b_.CreateLoad(lt(t), out);
    }
    case BuiltinOp::Convert:
      return convert(a[0], rv.ops[0].type, rv.type);
    case BuiltinOp::CStr:
      return viaOut("co_str_from_cstr", {ptrTy_}, {a[0]});
    case BuiltinOp::MakeError:
      return viaOut("co_str_clone", {ptrTy_}, {a[0]});
    case BuiltinOp::MapGet: {
      Type *m = rv.ops[0].type->inner;
      llvm::Value *p = b_.CreateCall(rt("co_map_get", ptrTy_, {ptrTy_, ptrTy_, i32_, i64_, i64_}),
                                     mapArgs(m, {a[0], a[1]}));
      // Build ?V (or ?&V) from the possibly-null value pointer.
      Type *opt = rv.type;
      llvm::Type *ot = lt(opt);
      llvm::Value *out = entryAlloca(ot);
      b_.CreateStore(llvm::Constant::getNullValue(ot), out);
      auto *found = llvm::BasicBlock::Create(ctx_, "found", fn_);
      auto *done = llvm::BasicBlock::Create(ctx_, "lookup.done", fn_);
      b_.CreateCondBr(b_.CreateIsNotNull(p), found, done);
      b_.SetInsertPoint(found);
      b_.CreateStore(llvm::ConstantInt::get(i64_, 1), b_.CreateStructGEP(ot, out, 0));
      Type *inner = opt->en->optionalOf;
      llvm::Value *payload = b_.CreateStructGEP(variantTy(opt, 1), b_.CreateStructGEP(ot, out, 1), 0);
      b_.CreateStore(inner->isRef() ? p : b_.CreateLoad(lt(inner), p), payload);
      b_.CreateBr(done);
      b_.SetInsertPoint(done);
      return b_.CreateLoad(ot, out);
    }
    case BuiltinOp::MapSlot: {
      Type *m = rv.ops[0].type->inner;
      return b_.CreateCall(rt("co_map_slot", ptrTy_, {ptrTy_, ptrTy_, i32_, i64_, i64_}), mapArgs(m, {a[0], a[1]}));
    }
    case BuiltinOp::MapDelete: {
      Type *m = rv.ops[0].type->inner;
      llvm::Value *tmp = entryAlloca(lt(m->inner));
      std::vector<llvm::Value *> args = mapArgs(m, {a[0], a[1]});
      args.push_back(tmp);
      llvm::Value *found = b_.CreateCall(rt("co_map_delete", i32_, {ptrTy_, ptrTy_, i32_, i64_, i64_, ptrTy_}), args);
      if (m->inner->needsDrop()) {
        auto *drop = llvm::BasicBlock::Create(ctx_, "deleted", fn_);
        auto *done = llvm::BasicBlock::Create(ctx_, "delete.done", fn_);
        b_.CreateCondBr(b_.CreateICmpNE(found, llvm::ConstantInt::get(i32_, 0)), drop, done);
        b_.SetInsertPoint(drop);
        b_.CreateCall(dropFn(m->inner), {tmp});
        b_.CreateBr(done);
        b_.SetInsertPoint(done);
      }
      return nullptr;
    }
    case BuiltinOp::MapUsed:
      return b_.CreateCall(rt("co_map_used", i64_, {ptrTy_}), {a[0]});
    case BuiltinOp::MapAlive: {
      llvm::Value *alive = mapAt(b_, "co_map_alive", i32_, rv.ops[0].type->inner, a[0], a[1]);
      return b_.CreateICmpNE(alive, llvm::ConstantInt::get(i32_, 0));
    }
    case BuiltinOp::MapKeyAt:
    case BuiltinOp::MapValAt: {
      Type *m = rv.ops[0].type->inner;
      const char *fn = rv.builtin == BuiltinOp::MapKeyAt ? "co_map_key_at" : "co_map_val_at";
      llvm::Value *p = mapAt(b_, fn, ptrTy_, m, a[0], a[1]);
      return rv.type->isRef() ? p : b_.CreateLoad(lt(rv.type), p);
    }
    case BuiltinOp::ToStr:
      switch (rv.ops[0].type->derefAll()->kind) {
      case TypeKind::Error: return viaOut("co_str_clone", {ptrTy_}, {a[0]});
      case TypeKind::Int: return viaOut("co_str_from_int", {i64_}, {a[0]});
      case TypeKind::IntN:
        if (rv.ops[0].type->isUnsigned)
          return viaOut("co_str_from_uint", {i64_}, {b_.CreateZExt(a[0], i64_)});
        return viaOut("co_str_from_int", {i64_}, {b_.CreateSExt(a[0], i64_)});
      case TypeKind::Float: return viaOut("co_str_from_float", {f64_}, {a[0]});
      case TypeKind::Float32: return viaOut("co_str_from_float", {f64_}, {b_.CreateFPExt(a[0], f64_)});
      default: return viaOut("co_str_from_bool", {i32_}, {b_.CreateZExt(a[0], i32_)});
      }
    case BuiltinOp::Panic:
      b_.CreateCall(rt("co_panic_str", void_, {ptrTy_}), {a[0]});
      return nullptr;
    case BuiltinOp::StrLit: {
      llvm::Value *g = b_.CreateGlobalString(rv.strLit, "str");
      return viaOut("co_str_lit", {ptrTy_, i64_}, {g, llvm::ConstantInt::get(i64_, rv.strLit.size())});
    }
    case BuiltinOp::StrConcat:
      return viaOut("co_str_concat", {ptrTy_, ptrTy_}, {a[0], a[1]});
    case BuiltinOp::StrCmp: {
      llvm::Value *c = b_.CreateCall(rt("co_str_cmp", i64_, {ptrTy_, ptrTy_}), {a[0], a[1]});
      llvm::Value *zero = llvm::ConstantInt::get(i64_, 0);
      return binary(rv.cmp, false, true, c, zero);
    }
    }
    return nullptr;
  }

  void dropLocal(int local) {
    auto *yes = llvm::BasicBlock::Create(ctx_, "drop", fn_);
    auto *done = llvm::BasicBlock::Create(ctx_, "drop.done", fn_);
    b_.CreateCondBr(b_.CreateLoad(i1_, flags_[local]), yes, done);
    b_.SetInsertPoint(yes);
    b_.CreateCall(dropFn(f_->locals[local].type), {slots_[local]});
    b_.CreateStore(b_.getFalse(), flags_[local]);
    b_.CreateBr(done);
    b_.SetInsertPoint(done);
  }

  void emitStmt(const Statement &s) {
    switch (s.kind) {
    case Statement::Assign: {
      llvm::Value *v = rvalue(s.rv);
      Type *ty = f_->locals[s.place.local].type;
      if (ty->kind == TypeKind::Void)
        return;
      if (s.place.isLocal()) {
        if (flags_[s.place.local]) {
          dropLocal(s.place.local); // drop the previous value, if any
          b_.CreateStore(b_.getTrue(), flags_[s.place.local]);
        }
        b_.CreateStore(v, slots_[s.place.local]);
      } else {
        llvm::Value *a = addr(s.place, ty);
        if (ty->needsDrop())
          b_.CreateCall(dropFn(ty), {a});
        b_.CreateStore(v, a);
      }
      return;
    }
    case Statement::Drop:
      if (flags_[s.place.local])
        dropLocal(s.place.local);
      return;
    case Statement::StorageDead:
    case Statement::Nop:
      return;
    }
  }

  void emitTerm(const Terminator &t) {
    switch (t.kind) {
    case Terminator::Goto:
      b_.CreateBr(bbs_[t.target]);
      break;
    case Terminator::If:
      b_.CreateCondBr(operand(t.cond), bbs_[t.thenBB], bbs_[t.elseBB]);
      break;
    case Terminator::Return:
      if (f_->info->ret->kind == TypeKind::Void)
        b_.CreateRetVoid();
      else
        b_.CreateRet(b_.CreateLoad(lt(f_->info->ret), slots_[0]));
      break;
    case Terminator::Unreachable:
      b_.CreateUnreachable();
      break;
    }
  }
};

// Loads the embedded runtime into `ctx`, retargeted to `mod`'s target.
std::unique_ptr<llvm::Module> loadRuntime(llvm::LLVMContext &ctx, const llvm::Module &mod, std::string &error) {
  llvm::StringRef bytes(reinterpret_cast<const char *>(runtimeBitcode), runtimeBitcodeSize);
  auto rt = llvm::parseBitcodeFile(llvm::MemoryBufferRef(bytes, "runtime.bc"), ctx);
  if (!rt) {
    error = "internal compiler error: cannot load the runtime: " + llvm::toString(rt.takeError());
    return nullptr;
  }
  (*rt)->setTargetTriple(mod.getTargetTriple());
  (*rt)->setDataLayout(mod.getDataLayout());
  // clang tags functions with the CPU it compiled for. Generated code has no
  // such tags, and LLVM won't inline a function into one with fewer features.
  for (llvm::Function &f : **rt)
    f.removeFnAttrs(llvm::AttributeMask().addAttribute("target-cpu").addAttribute("target-features").addAttribute(
        "tune-cpu"));
  return std::move(*rt);
}

} // namespace

bool emitObject(const mir::Module &m, const std::string &objPath, const CodegenOptions &opts, std::string &error) {
  llvm::InitializeNativeTarget();
  llvm::InitializeNativeTargetAsmPrinter();
  llvm::InitializeNativeTargetAsmParser(); // for the _start asm of LinkPlan

  llvm::Triple triple(llvm::sys::getDefaultTargetTriple());
  const llvm::Target *target = llvm::TargetRegistry::lookupTarget(triple, error);
  if (!target)
    return false;
  llvm::TargetOptions topts;
  auto level = opts.optLevel == 0 ? llvm::CodeGenOptLevel::None
             : opts.optLevel == 1 ? llvm::CodeGenOptLevel::Less
                                  : llvm::CodeGenOptLevel::Default;
  std::unique_ptr<llvm::TargetMachine> tm(
      target->createTargetMachine(triple, "generic", "", topts, llvm::Reloc::PIC_, std::nullopt, level));

  llvm::LLVMContext ctx;
  llvm::Module mod("co", ctx);
  mod.setTargetTriple(triple);
  mod.setDataLayout(tm->createDataLayout());

  std::unique_ptr<llvm::Module> runtime = loadRuntime(ctx, mod, error);
  if (!runtime)
    return false;

  CodeGen cg(ctx, mod, *runtime);
  cg.run(m);

  std::string verr;
  llvm::raw_string_ostream vos(verr);
  if (llvm::verifyModule(mod, &vos)) {
    error = "internal compiler error: invalid LLVM IR generated:\n" + verr;
    return false;
  }

  // Link the runtime in and hide everything but `main`, so the optimizer sees
  // the whole program: runtime calls inline and unused code disappears.
  if (llvm::Linker::linkModules(mod, std::move(runtime))) {
    error = "internal compiler error: cannot link the runtime";
    return false;
  }
  llvm::internalizeModule(mod, [](const llvm::GlobalValue &gv) { return gv.getName() == "main"; });
  if (!opts.startAsm.empty())
    mod.appendModuleInlineAsm(opts.startAsm);

  if (opts.optLevel > 0) {
    llvm::LoopAnalysisManager lam;
    llvm::FunctionAnalysisManager fam;
    llvm::CGSCCAnalysisManager cgam;
    llvm::ModuleAnalysisManager mam;
    llvm::PassBuilder pb(tm.get());
    pb.registerModuleAnalyses(mam);
    pb.registerCGSCCAnalyses(cgam);
    pb.registerFunctionAnalyses(fam);
    pb.registerLoopAnalyses(lam);
    pb.crossRegisterProxies(lam, fam, cgam, mam);
    auto ol = opts.optLevel == 1 ? llvm::OptimizationLevel::O1
            : opts.optLevel == 2 ? llvm::OptimizationLevel::O2
                                 : llvm::OptimizationLevel::O3;
    llvm::ModulePassManager mpm = pb.buildPerModuleDefaultPipeline(ol);
    mpm.run(mod, mam);
  }

  if (!opts.llvmIrPath.empty()) {
    std::error_code ec;
    llvm::raw_fd_ostream irOut(opts.llvmIrPath, ec, llvm::sys::fs::OF_Text);
    if (ec) {
      error = "cannot write " + opts.llvmIrPath + ": " + ec.message();
      return false;
    }
    mod.print(irOut, nullptr);
  }

  std::error_code ec;
  llvm::raw_fd_ostream out(objPath, ec, llvm::sys::fs::OF_None);
  if (ec) {
    error = "cannot write " + objPath + ": " + ec.message();
    return false;
  }
  llvm::legacy::PassManager pm;
  if (tm->addPassesToEmitFile(pm, out, nullptr, llvm::CodeGenFileType::ObjectFile)) {
    error = "target cannot emit object files";
    return false;
  }
  pm.run(mod);
  out.flush();
  return true;
}

} // namespace co
